# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Azure Extension for TTT AutoRun@23
  inputs:
      HCIConnection: 'CW01.BMC.COM'
      HCIConnectionPort: '16196'
      UserID: 'PINAWM1'
      Password: 'Moab22'
      TestLocationPath: 'C:\Users\amohapat\Testing\CLITestInAzureExt\PartecisTesting\Scenarios'
      CLIInstallationPath: 'C:\Topaz\WorkbenchCLI\20.12.02.99'
      Configuration: 'LocalTTTConf'
      LocalTTTConfiguration: 'C:\Topaz\TotalTestConfiguration'

